name: Sedstart1 QA

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: sedstart/runcloud@main
        with:
          api_key: ${{ secrets.SEDSTART_API_KEY_QA }}
          project_id: 503
          test_id: 2432
          suite_id: 441
          profile_id: 1007
          browser: chrome
          headless: false
          environment: QA
